### ISSUE TITLE
Correct way to fully rebuild a ZOS deployment?  Also, possible bug in ZOS client.

### ISSUE THREAD

**Issue by roschler** [zeppelinos/zos-cli#247]
What is the correct way to fully rebuild a deployment, as in the case if you have to shut down the Ganache client for some reason?  I tried using `zos upgrade --all` but it kept trying to use the old `app` address, which belonged to the old Ganache client memory image and was no longer valid.  This resulted in a "not a contract address" exception being thrown.  You get the same error when trying to do a `zos push` of course since it tries to use the old stale `app` address found in `zos.local.json`.

I then tried removing the `zos.local.json` file and using `zos push` again.  This seemed to work except after deploying, for some reason it tried to open `zos.local.json` in the `openzeppelin-zos` directory under _node_modules_.   Since that file doesn't exist, it threw a bunch of errors (see below).

What's the correct command or steps to rebuild your Ganache client state after restarting the Ganache client?

```sh
$  rm zos.local.json
$  npx zos upnpx zos push --from $OWNER --network local
Compiling contracts
Compiling ./contracts/Basil.sol...
Compiling ./contracts/BasilERC721.sol...
Compiling openzeppelin-zos/contracts/AddressUtils.sol...
Compiling openzeppelin-zos/contracts/math/SafeMath.sol...
Compiling openzeppelin-zos/contracts/ownership/Ownable.sol...
Compiling openzeppelin-zos/contracts/token/ERC721/ERC721.sol...
Compiling openzeppelin-zos/contracts/token/ERC721/ERC721Basic.sol...
Compiling openzeppelin-zos/contracts/token/ERC721/ERC721BasicToken.sol...
Compiling openzeppelin-zos/contracts/token/ERC721/ERC721Receiver.sol...
Compiling openzeppelin-zos/contracts/token/ERC721/ERC721Token.sol...
Compiling openzeppelin-zos/contracts/token/ERC721/MintableERC721Token.sol...
Compiling zos-lib/contracts/migrations/Migratable.sol...
Writing artifacts to ./build/contracts

Deploying new UpgradeabilityProxyFactory...
Deployed UpgradeabilityProxyFactory 0xe78a0f7e598cc8b0bb87894b0f60dd2a88d6a8ab
Deploying new Package...
Deployed Package 0x5b1869d9a4c187f2eaa108f3062412ecf0526b24
Deploying new AppDirectory...
Deployed AppDirectory 0xcfeb869f69431e42cdb54a4f4f105c19c080a601
Adding new version...
Added version 0.0.2
Deploying new PackagedApp...
Deployed PackagedApp 0xc89ce4735882c9f0f0fe26686c53074e09b0d550
Uploading BasilERC721 contract as Basil
Setting implementation of Basil in directory...
 Implementation set: 0xd833215cbcc3f914bd1c9ece3ee7bf8b14f841bb
Connecting to public deployment of openzeppelin-zos in local
Successfully written zos.local.json
Error: ENOENT: no such file or directory, open 'node_modules/openzeppelin-zos/zos.local.json'
    at Object.fs.openSync (fs.js:577:3)
    at Object.fs.readFileSync (fs.js:483:33)
    at read (/home/robert/Documents/GitHub/ME/zeppelin-os-work/basil/node_modules/zos/node_modules/zos-lib/lib/utils/FileSystem.js:26:23)
    at Object.parseJson (/home/robert/Documents/GitHub/ME/zeppelin-os-work/basil/node_modules/zos/node_modules/zos-lib/lib/utils/FileSystem.js:50:21)
    at Object.from (/home/robert/Documents/GitHub/ME/zeppelin-os-work/basil/node_modules/zos/lib/models/stdlib/StdlibProvider.js:12:44)
    at Function.fetch (/home/robert/Documents/GitHub/ME/zeppelin-os-work/basil/node_modules/zos/lib/models/stdlib/Stdlib.js:29:37)
    at NetworkAppController.linkStdlib (/home/robert/Documents/GitHub/ME/zeppelin-os-work/basil/node_modules/zos/lib/models/network/NetworkAppController.js:198:44)
    at NetworkAppController.push (/home/robert/Documents/GitHub/ME/zeppelin-os-work/basil/node_modules/zos/lib/models/network/NetworkAppController.js:60:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
Here is the contents of my `zos.local.json` file after the re-deploy:

```json
$  cat zos.local.json
{
  "contracts": {
    "Basil": {
      "address": "0xd833215cbcc3f914bd1c9ece3ee7bf8b14f841bb",
      "bytecodeHash": "24e8d82d349e27d0edd92397cde3653b407ec238323864436f0ae1373cf7e743"
    }
  },
  "proxies": {},
  "app": {
    "address": "0xc89ce4735882c9f0f0fe26686c53074e09b0d550"
  },
  "version": "0.0.2",
  "package": {
    "address": "0x5b1869d9a4c187f2eaa108f3062412ecf0526b24"
  },
  "provider": {
    "address": "0xcfeb869f69431e42cdb54a4f4f105c19c080a601"
  }
```

**Comment by facuspagnuolo** [comment]
Sorry for the late response @roschler. Unfortunately, the CLI does not provide support to rebuild a zOS deployment scenario. We are going to start working on https://github.com/zeppelinos/zos/issues/35 but it is mostly for other networks than local ones. In order to make sure you are working with the same addresses every time you start a new ganache client, you can configure a custom mnemonic and use the same deployment script to set it up.

**Comment by facuspagnuolo** [comment]
Considering the answer above, since there was no more activity, we are closing this issue. If there are any further questions please open a new one. Thanks!
