### ISSUE TITLE
Error when running npm install on app that depends on CLI

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos-cli#46]
Reported by @ajsantander, error is:

```npm i                                                                            (refactor/new_model✱) 
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers

> zos@0.3.13 prepack /home/ajs/.npm/_cacache/tmp/git-clone-7ff52d39
> truffle compile && sed -i.bak 's/\/src/\/lib/g' bin/zos-cli.js && rm bin/zos-cli.js.bak && babel src --out-dir lib

Error: Cannot find module 'babel-register'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ajs/.npm/_cacache/tmp/git-clone-7ff52d39/truffle.js:1:63)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: zos-cli@git://github.com/zeppelinos/cli.git#master.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ajs/.npm/_logs/2018-04-25T19_13_18_940Z-debug.log```
```

Most likely the problem is that the npm install is triggering the [prepack](https://docs.npmjs.com/misc/scripts) step of zos-cli, which involves truffle compile, which requires babel register, which is not installed at this point.

This should be fixed by changing the script from prepack to prepublishOnly [here](https://github.com/zeppelinos/zos-cli/blob/master/package.json#L7), so the compilation is only triggering when building the package.

Check that it solves the issue, and publish a new version with the fix.

**Comment by spalladino** [comment]
Not reproducible as of `v0.3.17`. Closing.
